### ISSUE TITLE
Controller Not Working on Gallagher's Gallery

### ISSUE THREAD

**Issue by mrobss** [DirtBagXon/hypseus_singe_data#16] opened 2024-12-27 20:30 UTC
I'm on a RetroPie build with the latest version of Hypseus installed.

If I load up Mad Dog, for example, I can use my XBOX 360 D-Pad to control the cursor on screen and the buttons to shoot.

On Gallagher's only the analog stick works, and it's all over the place, and none of the buttons fire.  

I thought all games pulled from the same controller config?

How can I get Gallagher to perform the same way as Mad Dog?

Thank you.

EDIT: Gallagher works just fine with the mouse, but not the controller's D-Pad.

**Comment by DirtBagXon** [comment] 2024-12-27 22:56
Hey thanks for the feedback. 

Can you please provide the **full** argument list you are using from `/dev/shm/runcommand.log` and also the `hypinput.ini` file you are using so we can track this down.

Thanks.

**Comment by DirtBagXon** [comment] 2024-12-27 22:59
Also, you mention "_Mad Dog_" - is this the recent 2-Player version you are referring to that works correctly ?

**Comment by mrobss** [comment] 2024-12-27 23:05
> Also, you mention "_Mad Dog_" - is this the recent 2-Player version you are referring to that works correctly ?

No, sorry, the original one you guys posted a while ago. I only have one analog / light gun controller so I never updated to the 2 player one.  Hang on let me grab those ini files for you...

**Comment by mrobss** [comment] 2024-12-27 23:09
> Hey thanks for the feedback.
> 
> Can you please provide the **full** argument list you are using from `/dev/shm/runcommand.log` and also the `hypinput.ini` file you are using so we can track this down.
> 
> Thanks.

Here's my hypinput.ini:
[KEYBOARD]
KEY_UP = 273 114 14
KEY_DOWN = 274 102 15
KEY_LEFT = 276 100 16
KEY_RIGHT = 275 103 17
KEY_BUTTON1 = 306 97 2
KEY_BUTTON2 = 308 115 1
KEY_BUTTON3 = 32 113 3
KEY_START1 = 49 0 8
KEY_START2 = 50 0 0
KEY_COIN1 = 53 0 7
KEY_COIN2 = 54 0 0
KEY_SKILL1 = 304 119 1
KEY_SKILL2 = 122 105 2
KEY_SKILL3 = 120 107 3
KEY_SERVICE = 57 0 0
KEY_TEST = 283 0 0
KEY_RESET = 284 0 0
KEY_SCREENSHOT = 293 0 0
KEY_QUIT = 27 113 0 0
END

And here's the runcommand log:
Executing: /opt/retropie/emulators/hypseus/hypseus.sh "/home/pi/RetroPie/roms/daphne/gallagher.daphne"
[version] Hypseus Singe: v2.11.3-RPi
[console] Setting alternate home dir: /opt/retropie/emulators/hypseus
2024-12-27 18:08:29.120 INFO  [2042] [reset_logfile@343] Version v2.11.3-RPi
2024-12-27 18:08:29.120 INFO  [2042] [reset_logfile@347] Command line: /opt/retropie/emulators/hypseus/hypseus.bin singe vldp -retropath -manymouse -script /home/pi/RetroPie/roms/daphne/gallagher.daphne/gallagher.zip -framefile /home/pi/RetroPie/roms/daphne/gallagher.daphne/gallagher.txt -homedir /opt/retropie/emulators/hypseus -fullscreen 
2024-12-27 18:08:29.120 INFO  [2042] [reset_logfile@348] CPU : UnknownCPU || Mem : 3968 megs
2024-12-27 18:08:29.122 INFO  [2042] [reset_logfile@349] OS : Linux 6.6 || Video : Unknown video
2024-12-27 18:08:29.123 INFO  [2042] [reset_logfile@350] RGB2YUV Function: C
2024-12-27 18:08:29.123 INFO  [2042] [reset_logfile@356] Line Blending Function: C
2024-12-27 18:08:29.123 INFO  [2042] [reset_logfile@363] Audio Mixing Function: C
2024-12-27 18:08:29.190 INFO  [2042] [CFG_Keys@240] Joystick HAT enabled on stick: [0]
2024-12-27 18:08:29.190 INFO  [2042] [manymouse_init_mice@359] Using ManyMouse for mice input.
2024-12-27 18:08:29.267 INFO  [2042] [manymouse_init_mice@376] Only 1 mouse found.
2024-12-27 18:08:29.267 INFO  [2042] [manymouse_init_mice@389] #0: Microsoft X-Box 360 pad
2024-12-27 18:08:32.638 INFO  [2042] [video::notify_stats@2191] Viewport Stats:|w:640x480|v:640x480|o:320x240|l:1920x1080|o
2024-12-27 18:08:33.638 INFO  [2042] [ldp_vldp::read_frame_conversions@1030] Framefile parse succeeded. Video/Audio directory is: /home/pi/RetroPie/roms/daphne/gallagher.daphne/./
2024-12-27 18:08:33.659 INFO  [2042] [printline@95] Starting Singe version 1.90
2024-12-27 18:08:33.660 INFO  [2042] [printline@95] SINGE: Loading ZIP based ROM
2024-12-27 18:08:34.110 INFO  [2042] [printline@95] SINGE: Singe version compatible with ratio adjustment.

Hopefully you can let me know what I'm doing wrong. I'm not as good with this stuff as you guys all are!  Thank you!

**Comment by DirtBagXon** [comment] 2024-12-27 23:24
Ok, the newer games are really designed to work with mice, so it appears the `-manymouse` argument is currently breaking the Gamepad ability to use certain controls in the 2 player games. The answer is when using a gamepad to remove the `-manymouse` argument.

In retropie this is hardcoded in: `/opt/retropie/emulators/hypseus/hypseus.sh`

Unfortunately there is no way to negate the argument later on in `.commands` files, so the fix for the moment is to **remove `-manymouse` from that script**. This of course will break your "light gun control" as that relies on ManyMouse to provide absolute mouse co-ordinates. You could add it back in via a `.commands` file when you want to use the lightgun, but it's not ideal.

I will look to see if the next release can offer an argument to negate `-manymouse` but it might be more trouble than it's worth.

In the meantime alter `/opt/retropie/emulators/hypseus/hypseus.sh` to get you going if that is the route you want to take.

**Comment by mrobss** [comment] 2024-12-27 23:35
Oh this works great!  Yeah I took that out of hypseus.sh and now the D-pad works along with the mouse.  Perfect!  Thank you!

One other question - 

With my controller config, I noticed that if I'm using the XBOX 360 controller, SELECT + START are my coin/start/exit buttons, but if I connect my Logitech F310 then my L2/R2 buttons are coin/start/exit buttons.

Is there any way to fix that other than re-mapping the .ini file?

**Comment by DirtBagXon** [comment] 2024-12-28 00:15
These config questions are best asked in the Discord, this channel is for issues with game code. So please jump on Discord.

For a quick answer and from your config ini above you are using Joystick API style config, this is different for every controller as you can see. If you use the `-gamepad` argument and Gamepad config, then by design, the controller buttons no matter what hardware, will be in the same place (provided they are "_game controllers_").

**Closed** 2024-12-28 00:16 UTC

**Comment by mrobss** [comment] 2024-12-28 02:29
Thanks! DirtBagXon!  Your -gamepad quick answer pointed me in the right direction and I got it all working!

**Comment by DirtBagXon** [comment] 2025-01-22 10:58
> _Unfortunately there is no way to negate the argument later on in .commands files, so the fix for the moment is to remove `-manymouse` from that script - `/opt/retropie/emulators/hypseus/hypseus.sh` ._

Just adding a footnote to this issue, to state that from `v2.11.4` of Hypseus, the `-nomanymouse` argument was added. This can now be added to a `.commands` file, so there is no longer a need to remove the predefined argument from the distribution scripts as suggested above.
